### ISSUE TITLE
Add linter and run it on CI

### ISSUE THREAD

**Issue by dodo5522** [dodo5522/blog-tech#3]
- [x] Add linter configuration
- [x] Lint on CI
- [x] Fix issues raised by linter
  - Make some issues TODOs

**Comment by dodo5522** [comment]
こうしてもよい

```yaml
name: Lint
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: node:20.9.0-bullseye-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint files in the repository
        run: |
          yarn install
          yarn lint
```

**Comment by dodo5522** [comment]
こうしてもよいらしい。
こちらの方がコンテナイメージをpullする必要がない分早そう。

refs:
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution#example-only-run-job-for-specific-repository

```yaml
name: Lint
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Lint-On-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: node:20.9.0-bullseye-slim
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
      - name: Lint files in the repository
        run: |
          yarn install
          yarn lint
```
